### ISSUE TITLE
generator.py - TypeError: __init__() got an unexpected keyword argument 'text'

### ISSUE THREAD

**Issue by avico78** [brokenloop/jsontopydantic#1]
Python 3.8.8,
I'm trying to run the generator.py by itself and getting error:
```

root@a21f0d01a432:/webserver/myTest# python3 generator.py
Traceback (most recent call last):
  File "gen.py", line 30, in <module>
    result = translate(data)
  File "gen.py", line 18, in translate
    parser = JsonSchemaParser(
TypeError: __init__() got an unexpected keyword argument 'text'

```
can you tell what could be the reason?

**Comment by brokenloop** [comment]
It sounds like you don't have the correct version of `datamodel-code-generator` installed - this project currently relies upon version `0.5.39`, although this will change in the near future.

**Comment by avico78** [comment]
Thanks @brokenloop ,
Tested with 0.5.39 - working ,
Failed on  0.9.4
