### ISSUE TITLE
Why import both annotations and List?

### ISSUE THREAD

**Issue by cclauss** [brokenloop/jsontopydantic#11]
If `annotations` has been imported then `dict`, `list`, `set`, `tuple` will work instead of `Dict`, `List`, `Set`, `Tuple`.

**Comment by brokenloop** [comment]
Hi @cclauss, thanks for your question. I'm assuming you're referring to the imports in the generated python code. 

To answer simply, jsontopydantic relies on [datamodel-code-generator](https://github.com/koxudaxi/datamodel-code-generator) for code generation, and their output imports annotations by default (as of version 0.11.6 at least).

**Comment by cclauss** [comment]
Got it...  Thanks.  Cool tool.
