### ISSUE TITLE
collaboration issues

### ISSUE THREAD

**Issue by matthieudesprez** [brokenloop/jsontopydantic#3]
Hi,

First of all, thanks for creating and deploying this project.

I'd like to contribute with a new feature to take advantage of Optional + snake_cased handling from datamodel-code-generator as I used it a lot locally, but I don't seem to have the right access to push anything to this repository.

Is there a specific setting that prevents me to do so ?

**Comment by brokenloop** [comment]
Hi there,

Thanks for your interest in contributing to this project! The best way for you to propose changes would be to fork the repository, and create a pull request from there. You can find more information on how to create a pull request from a fork [here](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork). 

Let me know if you have any issues.

**Comment by matthieudesprez** [comment]
Thanks, didn't know it was possible.

I've created the PR.

**Comment by brokenloop** [comment]
Looks great! Thanks for the PR.
