### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by jordansafer** [brokenloop/jsontopydantic#8]
Hi! I think this project & website are great, but I wasn't able to use them because there's no license. I ended up using datamodel-code-generator directly, with some additional effort, since I wasn't sure what the terms of use were from outputs from your code or website. I would love to use this in the future!

**Comment by brokenloop** [comment]
Hi @jordansafer, thanks for raising this issue and for the kind words. 

I have decided to license this project under MIT, which should be sufficiently permissive for you to use the website and its output for any purpose you see fit.

**Comment by jordansafer** [comment]
Amazing! Thank you!!
